apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
  namespace: banking
  labels:
    app: banking-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      name: banking-app
      labels:
        app: banking-app
    spec:
      containers:
        - name: banking-app
          image: venkatapadma26/banking-application:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:      # Setting Environment Variables
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: banking_db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root

          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2