services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: banking_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  app:
    image: banking-application:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banking_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4318:4318'
      - '4317:4317'