# Define a 'Service' to expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: mysql     # DNS name
spec:
  selector:       # mysql Pod should contain same labels
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None   # we use DNS, Thus ClusterIp is not relevant
  